apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: tbrif5y5n-go
  janus-idp.io/tekton: tbrif5y5n-go
  backstage.io/kubernetes-id: tbrif5y5n-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tbrif5y5n-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
