apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: tbrif5y5n-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tbrif5y5n-go 
  name: tbrif5y5n-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: tbrif5y5n-go 
