apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: tbrif5y5n-go 
  janus-idp.io/tekton: tbrif5y5n-go
  backstage.io/kubernetes-id: tbrif5y5n-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tbrif5y5n-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml